apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kvname
  namespace: default
spec:
  provider: azure
  secretObjects:
    - secretName: kv-secrets
      type: Opaque
      data:
        - objectName: inject-secret
          key: inject-secret
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    keyvaultName: keyvault-2bcloud
    tenantId: bd4f0481-b137-40f1-9e64-20cfd55fbf49
    objects: |
      array:
        - |
          objectName: inject-secret
          objectType: secret
    cloudName: ""
