apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-deployment
  namespace: web
  labels:
    app: hello-world
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world
        image: bcloudacr.azurecr.io/samples/python-image:latest
        resources:
          requests:
            cpu: "100m"  # Requesting 100 milliCPU
          limits:
            cpu: "500m"  # Limiting to 500 milliCPU

        ports:
        - containerPort: 80
    
